### ISSUE TITLE
detecting a printer

### ISSUE THREAD

**Issue by monad98** [ka2n/ptouchgo#6]
On linux/Mac OS machine how can I detect a printer connected via USB port?
I don't see any in `/dev/tty*`

**Comment by ka2n** [comment]
Linux should create a node like /dev/ttyUSB0 just by connecting it, but you may want to check if the device is recognized with commands like dmesg or lsusb.

ref: https://askubuntu.com/questions/334784/dev-ttyusb0-doesnt-exists

**Comment by monad98** [comment]
Thanks. Linux recognizes it immediately while MAC OS doesn't.
